#%RAML 1.0 Library

usage: Product Types

types:
  ProductSummaryType:
    displayName: Product Summary
    description: Definition of the Product Summary Object
    type: object
    properties: 
      uniqueId: 
        type: string
        displayName: UniqueId
        description: Unique Id of the Product
      name:
        type: string
        description: Name of the Product
      status:
        type: string
        description: Status of the Product