#%RAML 1.0 DataType

displayName: Order Summary
description: Definition of the Order Summary Object

type: object
properties:
  uniqueId:
    type: string
    displayName: UniqueId
    description: Unique Id of the Order
  summary:
    type: string
    description: Summary information of the Order
  status:
    type: string
    description: Status of the Order
