#%RAML 1.0 Trait

usage: Common Response type for get a resource operation

uses:
  responseTypes: ../libraries/ResponseTypes.raml

responses:
  200:
    body:
      application/json:
        type: <<getJsonType>>
    description: Get a resource
  400:
    body:
      application/json:
        type: responseTypes.ErrorResponseType
    description: Invalid input data
  401:
    body:
      application/json:
        type: responseTypes.ErrorType
    description: Unathorize action
  403:
    body:
      application/json:
        type: responseTypes.ErrorType
    description: Forbidden action
  404:
    body:
      application/json:
        type: responseTypes.ErrorType
    description: Resource not found
  500:
    body:
      application/json:
        type: responseTypes.ErrorResponseType
    description: Internal errors
    