#%RAML 1.0 DataType

displayName: ISO 3166-1 Alpha2 Country Codes

type:
  enum: [
  AF, # Afghanistan
  AX, # Aland Islands
  AL, # Albania
  DZ, # Algeria
  AS, # American Samoa
  AD, # Andorra
  AO, # Angola
  AI, # Anguilla
  AQ, # Antarctica
  AG, # Antigua and Barbuda	AG	ATG	028
  AR, # Argentina
  AM, # Armenia
  AW, # Aruba
  AU, # Australia
  AT, # Austria
  AZ, # Azerbaijan
  BS, # Bahamas
  BH, # Bahrain
  BD, # Bangladesh
  BB, # Barbados
  BY, # Belarus
  BE, # Belgium
  BZ, # Belize
  BJ, # Benin
  BM, # Bermuda
  BT, # Bhutan
  BO, # Bolivia
  BA, # Bosnia and Herzegovina
  BW, # Botswana
  BV, # Bouvet Island
  BR, # Brazil
  VG, # British Virgin Islands
  IO, # British Indian Ocean Territory
  BN, # Brunei Darussalam
  BG, # Bulgaria
  BF, # Burkina Faso
  BI, # Burundi
  KH, # Cambodia
  CM, # Cameroon
  CA, # Canada
  CV, # Cape Verde
  KY, # Cayman Islands
  CF, # Central African Republic
  TD, # Chad
  CL, # Chile
  CN, # China
  HK, # Hong Kong, SAR China
  MO, # Macao, SAR China
  CX, # Christmas Island
  CC, # Cocos (Keeling) Islands
  CO, # Colombia
  KM, # Comoros
  CG, # Congo (Brazzaville)
  CD, # Congo, (Kinshasa)
  CK, # Cook Islands
  CR, # Costa Rica
  CI, # Côte d'Ivoire
  HR, # Croatia
  CU, # Cuba
  CY, # Cyprus
  CZ, # Czech Republic
  DK, # Denmark
  DJ, # Djibouti
  DM, # Dominica
  DO, # Dominican Republic
  EC, # Ecuador
  EG, # Egypt
  SV, # El Salvador
  GQ, # Equatorial Guinea
  ER, # Eritrea
  EE, # Estonia
  ET, # Ethiopia
  FK, # Falkland Islands
  FO, # Faroe Islands
  FJ, # Fiji
  FI, # Finland
  FR, # France
  GF, # French Guiana
  PF, # French Polynesia
  TF, # French Southern Territories
  GA, # Gabon
  GM, # Gambia
  GE, # Georgia
  DE, # Germany
  GH, # Ghana
  GI, # Gibraltar
  GR, # Greece
  GL, # Greenland
  GD, # Grenada
  GP, # Guadeloupe
  GU, # Guam
  GT, # Guatemala
  GG, # Guernsey
  GN, # Guinea
  GW, # Guinea-Bissau
  GY, # Guyana
  HT, # Haiti
  HM, # Heard and Mcdonald Islands
  VA, # Holy See (Vatican City State)
  HN, # Honduras
  HU, # Hungary
  IS, # Iceland
  IN, # India
  ID, # Indonesia
  IR, # Iran
  IQ, # Iraq
  IE, # Ireland
  IM, # Isle of Man
  IL, # Israel
  IT, # Italy
  JM, # Jamaica
  JP, # Japan
  JE, # Jersey
  JO, # Jordan
  KZ, # Kazakhstan
  KE, # Kenya	KE
  KI, # Kiribati	KI
  KP, # Korea (North)	KP
  KR, # Korea (South)	KR
  KW, # Kuwait	KW
  KG, # Kyrgyzstan	KG
  LA, # Lao PDR	LA
  LV, # Latvia	LV
  LB, # Lebanon	LB
  LS, # Lesotho	LS
  LR, # Liberia	LR
  LY, # Libya	LY
  LI, # Liechtenstein	LI
  LT, # Lithuania	LT
  LU, # Luxembourg	LU
  MK, # Macedonia
  MG, # Madagascar	MG
  MW, # Malawi	MW
  MY, # Malaysia	MY
  MV, # Maldives	MV
  ML, # Mali	ML
  MT, # Malta	MT
  MH, # Marshall Islands	MH
  MQ, # Martinique	MQ
  MR, # Mauritania	MR
  MU, # Mauritius	MU
  YT, # Mayotte	YTM
  MX, # Mexico	MX
  FM, # Micronesia, Federated States of	FM
  MD, # Moldova	MD
  MD, # Monaco	MC
  MN, # Mongolia	MN
  ME, # Montenegro	ME
  MS, # Montserrat	MS
  MA, # Morocco	MA
  MZ, # Mozambique	MZ
  MM, # Myanmar	MM
  NA, # Namibia	NA
  NR, # Nauru	NR
  NP, # Nepal	NP
  NL, # Netherlands	NL
  AN, # Netherlands Antilles	AN
  NC, # New Caledonia	NC
  NZ, # New Zealand	NZ
  NI, # Nicaragua	NI
  NE, # Niger	NE
  NG, # Nigeria	NG
  NU, # Niue	NU
  NF, # Norfolk Island	NF
  MP, # Northern Mariana Islands	MP
  NO, # Norway	NO
  OM, # Oman	OM
  PK, # Pakistan	PK
  PW, # Palau	PW
  PS, # Palestinian Territory	PS
  PA, # Panama	PA
  PG, # Papua New Guinea	PG
  PY, # Paraguay	PY
  PE, # Peru	PE
  PH, # Philippines	PH
  PN, # Pitcairn	PN
  PL, # Poland	PL
  PT, # Portugal	PT
  PR, # Puerto Rico	PR
  QA, # Qatar	QA
  RE, # Réunion	RE
  RO, # Romania	RO
  RU, # Russian Federation	RU
  RW, # Rwanda	RW
  BL, # Saint-Barthélemy	BL
  SH, # Saint Helena	SH
  KN, # Saint Kitts and Nevis	KN
  LC, # Saint Lucia	LC
  MF, # Saint-Martin (French part)	MF
  PM, # Saint Pierre and Miquelon	PM
  VC, # Saint Vincent and Grenadines	VC
  WS, # Samoa	WS
  SM, # San Marino	SM
  ST, # Sao Tome and Principe	ST
  SA, # Saudi Arabia	SA
  SN, # Senegal	SN
  RS, # Serbia	RS
  SC, # Seychelles	SC
  SL, # Sierra Leone	SL
  SG, # Singapore	SG
  SK, # Slovakia	SK
  SI, # Slovenia	SI
  SB, # Solomon Islands	SB
  SO, # Somalia	SO
  ZA, # South Africa	ZA
  GS, # South Georgia and the South Sandwich Islands	GS
  SS, # South Sudan	SS
  ES, # Spain	ES
  LK, # Sri Lanka	LK
  SD, # Sudan	SD
  SR, # Suriname	SR
  SJ, # Svalbard and Jan Mayen Islands	SJ
  SZ, # Swaziland	SZ
  SE, # Sweden	SE
  CH, # Switzerland	CH
  SY, # Syrian Arab Republic (Syria)	SY
  TW, # Taiwan, Republic of China	TW
  TJ, # Tajikistan	TJ
  TZ, # Tanzania, United Republic of	TZ
  TH, # Thailand	TH
  TL, # Timor-Leste	TL
  TG, # Togo	TG
  TK, # Tokelau	TK
  TO, # Tonga	TO
  TT, # Trinidad and Tobago	TT
  TN, # Tunisia	TN
  TR, # Turkey	TR
  TM, # Turkmenistan	TM
  TC, # Turks and Caicos Islands	TC
  TV, # Tuvalu	TV
  UG, # Uganda	UG
  UA, # Ukraine	UA
  AE, # United Arab Emirates	AE
  GB, # United Kingdom	GB
  US, # United States of America	US
  UM, # US Minor Outlying Islands	UM
  UY, # Uruguay	UY
  UZ, # Uzbekistan	UZ
  VU, # Vanuatu	VU
  VE, # Venezuela (Bolivarian Republic)	VE
  VN, # Viet Nam	VN
  VI, # Virgin Islands, US	VI
  WF, # Wallis and Futuna Islands	WF
  EH, # Western Sahara	EH
  YE, # Yemen	YE
  ZM, # Zambia	ZM
  ZW, # Zimbabwe	ZW	ZWE	716
  ]
