#%RAML 1.0 SecurityScheme

uses:
  responseTypes: ../libraries/ResponseTypes.raml

type: OAuth 2.0
description: OAuth 2.0 Security Scheme using client credential grant type

describedBy:
  headers:
    Authorization:
      description: Authorization header will have the token
      type: string
  responses:
    401:
      body:
        application/json:
          type: responseTypes.ErrorType
      description: Unauthorise, Invalid access token
    403:
      body:
        application/json:
          type: responseTypes.ErrorType
      description: Forbidden, Don't have access privileges
settings:
  authorizationUri: <<authUrl>>
  accessTokenUri: <<tokenUrl>>
  authorizationGrants: client_credentials
