#%RAML 1.0 DataType

displayName: Customer
description: Definition of the Customer Object

type: object
properties:
  id:
    type: string
    required: false
    displayName: UniqueId
    description: Unique identifier for Customer record
  nameDetails:
    type: object
    displayName: Name Details
    description: Customer name information
    properties:
      salutation:
        type: string
        displayName: Salutation
        description: Salutation of the person
        required: false
      prefix:
        type: string
        displayName: Prefix
        description: Name prefix of the person
        required: false
      firstName:
        type: string
        displayName: First Name
        description: First name of the person
      middleName:
        type: string
        displayName: Middle Name
        description: Middle name of the person
        required: false
      lastName:
        type: string
        displayName: Last Name
        description: Last name of the person
  addressDetails:
    type: object
    displayName: Address Details
    description: Customer address information
    properties:
      addressLine1:
        type: string
        displayName: Address Line 1
        description: Field indicating street address
      addressLine2:
        type: string
        displayName: Address Line 2
        description: Field for additional information about address
        required: false
      addressLine3:
        type: string
        displayName: Address Line 3
        description: Field for additional information about address
        required: false
      addressLine4:
        type: string
        displayName: Address Line 4
        description: Field for additional information about address
        required: false
      addressLine5:
        type: string
        displayName: Address Line 5
        description: Field for additional information about address
        required: false
      cityDivision:
        type: string
        displayName: City Division
        description: Filed indicating Sub division / area of the City
        required: false
      city:
        type: string
        displayName: City
        description: City of the address
      state:
        type: string
        displayName: State
        description: State of the address
      postalCode:
        type: string
        displayName: Postal Code
        description: Postal code of the address
      country:
        type: string
        displayName: Country Code
        description: Country of the address
example: {"nameDetails":{"salutation": "Mr", "firstName": "John", "middleName": "H", "lastName": "Doe"},"addressDetails": { "addressLine1": "101 Main St.", "addressLine2": "Unit 1", "city": "Columbus", "state": "OH", "postalCode": "41068", "country": "US"}}
