#%RAML 1.0 Trait

usage: Common query parameter for indicating status

description: Provides query parameter to be used for <<purpose>>

queryParameters:
  <<statusParamName>>:
    type: string
    displayName: Status Filter
    description: Status param for <<purpose>>
    required: <<isRequired>>
